# Generated by Django 4.1.5 on 2023-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='username1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username11',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username12',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username13',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username14',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username15',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username16',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username17',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username18',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username19',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username20',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='username9',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
