# Generated by Django 4.1.5 on 2023-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_alter_database_username1_alter_database_username10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='username1',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username10',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username11',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username12',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username13',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username14',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username15',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username16',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username17',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username18',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username19',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username2',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username20',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username3',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username4',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username5',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username6',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username7',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username8',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='username9',
            field=models.BooleanField(default=False, max_length=50),
        ),
    ]
